#!/bin/bash

# TODO: resolve by ipv6 mcast instead
HOST_BASE=${HOST_BASE-"CZ"}
SSH_KEY=`dirname $BASH_SOURCE`/keys/ssh_key
# git doesn't preserve permissions on the included key
sudo su nobody -c 'test -r keys/ssh_key' && chmod 600 $SSH_KEY

error() {
	echo "<ERROR>"
	echo "$@"
	exit 1
}

nssh() {
	ssh -i $SSH_KEY $@
}
export nssh

nscp() {
	scp -i $SSH_KEY $@
}
export nscp

nenum() {
	avahi-browse -t -k _ssh._tcp | grep $HOST_BASE | cut -f9 -d' '
}
export nenum
