#!/bin/bash

source `dirname $0`/common
NODES=`nenum`
MESHIF=wlan0

usage() {
	echo "usage: $0 [-l] [-p]"
}

# parse station dump input into lines of format
# link,<local mac>,<peer mac>,<plink state>
parse_plinks() {
	local node=$1
	local input=`cat`
	# XXX: ash doesn't have arrays
	local stas=(`echo "$input" | grep Station | cut -f2 -d' '`)
	local plinks=(`echo "$input" | grep plink | awk '{print $3}'`)

	i=0
	count=${#stas[*]}
	while [ $i -lt $count ]; do
		echo "link,$node,${stas[$i]},${plinks[$i]}"
		i=$[i+1]
	done
}

while getopts "lp" opt; do
	case $opt in
		l)
			LINK=yes
			;;
		m)
			MPATH=yes
			;;
	esac
done

for node in $NODES; do
	MAC=`nssh root@$node.local "iw $MESHIF info | grep addr | cut -f2 -d' '"`

	if [ ! -z "$LINK" ]; then
		STAS=`nssh root@$node.local "iw $MESHIF station dump"`
		echo "$STAS" | parse_plinks $MAC
	fi

	# TODO: get mpaths
done
